#!/usr/bin/env bash



#
#chmod +x scripts/migrate-pages-to-docusaurus.sh

# Dry-run (ukáže, čo spraví), pre sk:
#scripts/migrate-pages-to-docusaurus.sh docs sk true

# Ostré spustenie pre sk:
#scripts/migrate-pages-to-docusaurus.sh docs sk

# Ak budeš migrovať aj en neskôr:
#scripts/migrate-pages-to-docusaurus.sh docs en
#Čo skript robí:

#nájde všetky .pages pod docs/sk (alebo docs/en),

#pre každý adresár vytvorí (ak chýba) _category_.json s labelom = názov priečinka a inkrementálnou position,

#(voliteľne) ak chýba index.md, vytvorí ho ako základný landing,

#odstráni všetky .pages (git-ovo aj z disku).
#___________________________________________________________________

#!/usr/bin/env bash
# Portable: works with macOS bash 3.2 / zsh / sh

set -euo pipefail

ROOT="${1:-docs}"      # koreň dokumentácie (default: docs)
LOCALE="${2:-sk}"      # jazykový podkoreň (default: sk)
DRY_RUN="${3:-false}"  # 'true' → len ukáž, čo by sa spravilo

echo ">>> MIGRATE .pages → _category_.json"
echo "ROOT=$ROOT  LOCALE=$LOCALE  DRY_RUN=$DRY_RUN"
echo

# 1) Zoznam .pages
PAGES_LIST="$(find "$ROOT/$LOCALE" -type f -name ".pages" 2>/dev/null | sort || true)"

if [ -z "$PAGES_LIST" ]; then
  echo "No .pages found under $ROOT/$LOCALE. Nothing to do."
  exit 0
fi

# 2) Unikátne priečinky so .pages (dirname; sort -u)
DIRS_LIST="$(printf "%s\n" "$PAGES_LIST" | xargs -I{} dirname "{}" | sort -u)"

# 3) Prejdi priečinky a vytvor _category_.json + index.md (ak chýbajú)
pos=1
echo "Creating/updating category metadata..."
printf "%s\n" "$DIRS_LIST" | while IFS= read -r dir; do
  [ -n "$dir" ] || continue
  label="$(basename "$dir")"
  cat_file="$dir/_category_.json"
  index_file="$dir/index.md"

  echo "→ $dir"
  echo "   will ensure: $cat_file  (position=$pos, label=$label)"

  if [ "$DRY_RUN" != "true" ]; then
    if [ ! -f "$cat_file" ]; then
      # create _category_.json
      printf '%s\n' "{
  \"label\": \"$label\",
  \"position\": $pos,
  \"collapsible\": true,
  \"collapsed\": false
}" > "$cat_file"
      echo "   created _category_.json"
    else
      echo "   _category_.json already exists → skipping"
    fi

    if [ ! -f "$index_file" ]; then
      # create landing index.md
      printf '%s\n' "--- 
id: index
title: $label
---

<!-- Autogenerated during migration from .pages. Add intro here. -->" > "$index_file"
      echo "   created index.md (landing)"
    fi
  fi

  pos=$((pos+1))
done

# 4) Odstráň .pages (git aj disk)
echo
echo "Cleaning up .pages files..."
if [ "$DRY_RUN" != "true" ]; then
  # odstráň trackované .pages z Gitu
  git ls-files -z -- "$ROOT/$LOCALE" | xargs -0 -I{} sh -c '
    case "$1" in
      */.pages) git rm -q "$1" >/dev/null 2>&1 || true ;;
    esac
  ' sh {}
  # odstráň z disku všetky .pages (trackované už budú preč)
  find "$ROOT/$LOCALE" -type f -name ".pages" -delete 2>/dev/null || true
else
  # DRY RUN výpis
  printf "%s\n" "$PAGES_LIST" | sed 's/^/   rm /'
fi

echo
echo "Done."
echo "Tip: commit changes:"
echo "  git commit -m \"chore: migrate MkDocs .pages to Docusaurus _category_.json (auto)\""
